- name: install Alpine cron job (ansible-pull), runs every 15min
  copy: src=files/cron_alpine.sh dest=/etc/periodic/15min owner=ansible group=ansible mode=0755
  when: ansible_distribution == 'Alpine' or ansible_distribution == 'Alpine'