- name: Install packages
  vars:
    sys_packages: [ 'linux-pam', 'htop', 'tmux', 'wget', 'curl', 'vim', 'git', 'ca-certificates', 'net-tools', 'bind-tools', 'jq']
  apk: name={{ sys_packages }} state=latest
