- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: update repositories
      yum: update_cache=yes
      changed_when: False
  # tasks:
  #   - name: check that i have log file for all hosts on my local machine
  #     stat: path=/var/log/hosts/{{inventory_hostname}}.log
  #     delegate_to: localhost.localdomain

  tasks:
    - include: tasks/groups.yml
    - include: tasks/users.yml
    - include: tasks/optimize.yml
    - include: tasks/yum/cron.yml
    - include: tasks/yum/packages.yml