- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apk:
        update_cache: yes

  tasks:
    - include: tasks/groups.yml
    - include: tasks/motd.yml
    - include: tasks/users.yml
    - include: tasks/apt/disable_auto_updates.yml
    - include: tasks/boot_optimization.yml
    - include: tasks/optimize.yml
    - include: tasks/apk/cron.yml
    - include: tasks/apk/packages.yml