- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      yum: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/groups.yml
    - include: tasks/motd.yml
    - include: tasks/users.yml
    - include: tasks/disable_auto_updates.yml
    - include: tasks/apt/boot_optimization.yml
    - include: tasks/optimize.yml
    - include: tasks/apt/cron.yml
    - include: tasks/apt/packages.yml