- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apk:
        update_cache: yes

  tasks:
    - include: tasks/apk/packages.yml
    - include: tasks/groups.yml
    - include: tasks/motd.yml
    - include: tasks/users.yml
    - include: tasks/ssh_access.yml
    - include: tasks/optimize.yml
    - include: tasks/apk/cron.yml
  
  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted