- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      yum: update_cache=yes
      changed_when: False

  tasks:
    - include_tasks: tasks/yum/packages.yml
    - include_tasks: tasks/groups.yml
    - include_tasks: tasks/motd.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/ssh_access.yml
    - include_tasks: tasks/boot_optimization.yml
    - include_tasks: tasks/optimize.yml
    - include_tasks: tasks/yum/cron.yml

  handlers:
    - name: restart ssh
      service: name=sshd
        state=restarted
