- hosts: all
  become: true
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - include_tasks: tasks/apt/packages.yml
    - include_tasks: tasks/groups.yml
    - include_tasks: tasks/motd.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/ssh_access.yml
    - include_tasks: tasks/apt/disable_auto_updates.yml
    - include_tasks: tasks/boot_optimization.yml
    - include_tasks: tasks/optimize.yml
    - include_tasks: tasks/apt/cron.yml
    - include_tasks: tasks/apt/fav_tools.yml # optional

  handlers:
    - name: restart ssh
      service: name=sshd
        state=restarted
