- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apk:
        update_cache: yes

  tasks:
    - include_tasks: tasks/apk/packages.yml
    - include_tasks: tasks/motd.yml
    - include_tasks: tasks/groups.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/ssh_access.yml
    - include_tasks: tasks/optimize.yml
    - include_tasks: tasks/apk/cron.yml

  handlers:
    - name: restart ssh
      service: name=sshd
        state=restarted
