- name: Check if the grub config file exists
  stat:
    path: /etc/default/grub
  register: grub_file

- name: Remove bootloader delay only if file exists
  replace:
    path: /etc/default/grub
    regexp: "GRUB_TIMEOUT=.*"
    replace: "GRUB_TIMEOUT=2"
  when: grub_file.stat.exists

- name: update-grub2 for Debian/Ubuntu
  shell: |
    update-grub2
  when: grub_file.stat.exists and ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: re-generate the /boot/grub2/grub.cfg file for RHEL/CentOS
  shell: |
    grub2-mkconfig –o /boot/grub2/grub.cfg
  when: grub_file.stat.exists and ansible_distribution == 'CentOS' or ansible_os_family == 'RedHat'
