- name: Ensure group "admin" exists
  group:
    name: admin
    state: present

- name: copy sudoers admin group for other distros
  copy: src=files/sudoers_admin dest=/etc/sudoers.d/admin owner=root group=root mode=0440
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Allow 'admin' group to have passwordless sudo for alpine
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
    when: ansible_distribution == 'Alpine' or ansible_distribution == 'Alpine'

- name: Make sure we have a 'wheel' group in alpine
  group:
    name: wheel
    state: present
    when: ansible_distribution == 'Alpine' or ansible_distribution == 'Alpine'

- name: Allow 'wheel' group to have passwordless sudo in alpine
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
    when: ansible_distribution == 'Alpine' or ansible_distribution == 'Alpine'