- name: Add the user 'ansible' and add to group 'ansible'
  user:
    name: ansible
    group: ansible
    shell: /bin/bash
    uid: 900
    comment: ansible user

- name: Add ansible user as sudoer, copy sudoers_ansible file 
  copy: src=files/sudoers_ansible dest=/etc/sudoers.d/ansible owner=root group=root mode=0440
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add ansible user as sudoer, using shell in Alpine
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%ansible'
    line: '%ansible ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  when: ansible_distribution == 'Alpine' or ansible_distribution == 'Alpine'

- name: Set authorized key for 'ansible' taken from file
  authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', 'files/id_rsa.pub') }}"

- name: Add the user 'Armand', appending the group 'admin' user's groups
  user:
    name: armand
    group: admin
    shell: /bin/bash
    append: yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add the user 'armand' with a primary group of 'admin', using shell in Alpine 
  shell: |
    addgroup armand admin
  when: ansible_distribution == 'Alpine' or ansible_distribution == 'Alpine'

- name: Add armand user as sudoer, copy sudoers_armand file  
  copy: src=files/sudoers_armand dest=/etc/sudoers.d/armand owner=root group=root mode=0440
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Set authorized key for 'armand' taken from file
  authorized_key:
    user: armand
    state: present
    key: "{{ lookup('file', 'files/id_rsa.pub') }}"
