- name: Add the user 'ansible'
  user:
    name: ansible
    uid: 900
    comment: ansible user

- name: copy sudoers_ansible
  copy: src=files/sudoers_ansible dest=/etc/sudoers.d/ansible owner=root group=root mode=0440
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


- name: Set authorized key for 'ansible' taken from file
  authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', 'files/id_rsa.pub') }}"

- name: Add the user 'armand' with a primary group of 'admin'
  user:
    name: armand
    comment: user in admin group
    group: admin
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Set authorized key for 'armand' taken from file
  authorized_key:
    user: armand
    state: present
    key: "{{ lookup('file', 'files/id_rsa.pub') }}"

- name: copy sudoers_armand
  copy: src=files/sudoers_armand dest=/etc/sudoers.d/armand owner=root group=root mode=0440
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
    when: ansible_distribution == 'Alpine' or ansible_distribution == 'Alpine'

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
    when: ansible_distribution == 'Alpine' or ansible_distribution == 'Alpine'

- name: Add sudoers users to wheel group
  user:
    name=ansible
    groups=wheel
    append=yes
    state=present
    createhome=yes
    when: ansible_distribution == 'Alpine' or ansible_distribution == 'Alpine'