- name: Install packages
  vars:
    sys_packages:
      [
        "jq",
        "yq",
        "httpie",
        "tig",
        "exa",
        "fd-find",
        "neofetch",
        "tmux",
        "bpytop",
        "duf",
        "rclone",
        "micro",
        "ripgrep",
        "silversearcher-ag",
        "tre-command",
      ]
  apt: name={{ sys_packages }} state=latest

# Install Hurl
- name: Set Hurl Version
  set_fact:
    hurl_version: "4.3.0"

- name: Download Hurl .deb file
  get_url:
    url: "https://github.com/Orange-OpenSource/hurl/releases/download/{{ hurl_version }}/hurl_{{ hurl_version }}_amd64.deb"
    dest: "/tmp/hurl_{{ hurl_version }}_amd64.deb"

- name: Update APT package index
  apt:
    update_cache: yes

- name: Install specific Hurl Version
  apt:
    deb: "/tmp/hurl_{{ hurl_version }}_amd64.deb"
    state: present

# Install fx
- name: Install fx
  shell: |
    curl https://fx.wtf/install.sh | sh
  args:
    executable: /bin/bash

# Install lnav
- name: Set lnav Version
  set_fact:
    lnav_version: "0.12.2"

- name: Download lnav .deb file
  get_url:
    url: "https://github.com/tstack/lnav/releases/download/v{{ lnav_version }}/lnav-{{ lnav_version }}-linux-musl-x86_64.zip"
    dest: "/tmp/lnav-{{ lnav_version }}-linux-musl-x86_64.zip"

- name: unzip lnav zip file
  shell: |
    unzip /tmp/lnav-{{ lnav_version }}-linux-musl-x86_64.zip
  args:
    executable: /bin/bash

- name: Check if lnav binary exists
  stat:
    path: /tmp/lnav-0.12.2/lnav
  register: lnav

- name: add lnav to bin
  command: mv /tmp/lnav-0.12.2/lnav /usr/bin
  when: lnav.stat.exists

# Install Doggo
- name: Install Doggo
  shell: |
    cd "$(mktemp -d)" \
    curl -sL "https://github.com/mr-karan/doggo/releases/download/v0.3.7/doggo_0.3.7_linux_amd64.tar.gz" | tar xz \
    mv doggo /usr/local/bin \
    cd ~
  args:
    executable: /bin/bash

# Install Lazygit
- name: Install Lazygit
  shell: |
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*') \
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" \
    tar xf lazygit.tar.gz lazygit \
    install lazygit /usr/local/bin \
  args:
    executable: /bin/bash

# Install gping
- name: Install gping
  shell: |
    echo 'deb [signed-by=/usr/share/keyrings/azlux.gpg] https://packages.azlux.fr/debian/ bookworm main' | sudo tee /etc/apt/sources.list.d/azlux.list \
    apt install gpg \
    curl -s https://azlux.fr/repo.gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/azlux.gpg > /dev/null \
    apt update \
    apt install gping
  args:
    executable: /bin/bash
# Install Navi
- name: Download and install Navi
  shell: |
    bash <(curl -sL https://raw.githubusercontent.com/denisidoro/navi/master/scripts/install)
  args:
    executable: /bin/bash

# Install diff-so-fancy
- name: Download and install Navi
  shell: |
    git clone https://github.com/so-fancy/diff-so-fancy diffsofancy
    chmod +x diffsofancy/diff-so-fancy
    mv diff-so-fancy /usr/bin
  args:
    executable: /bin/bash
