- name: Install packages
  vars:
    sys_packages: [ 'htop', 'tmux', 'wget', 'curl', 'vim', 'git', 'apt-transport-https', 'ca-certificates', 'unzip', 'dnsutils', 'jq']
  apt: name={{ sys_packages }} state=latest