- name: Install packages
  vars:
    sys_packages:
      [
        "sudo",
        "openssh-client",
        "openssh-server",
        "htop",
        "tmux",
        "wget",
        "curl",
        "vim",
        "git",
        "apt-transport-https",
        "ca-certificates",
        "unzip",
        "dnsutils",
        "net-tools",
        "resolvconf",
        "jq",
      ]
  apt: name={{ sys_packages }} state=latest
